### ISSUE TITLE
Installed Anaconda at the wrong place (Mac OSX)

### ISSUE THREAD

**Issue by pllim** [spacetelescope/JWSTUserTraining2016#12]
*"I tried to install Anaconda. However, I installed it in the /Applications/ dir instead of my home-dir. I gather from "The OS X GUI installer may cause side-effects, such as changing permissions of files in your home directory to root:wheel, or mistakenly creating a system-wide installation under /anaconda instead of your personal home directory. “ that it should have been in the home-dir instead? If so, how do I correct this?
Also, when I type ‘conda’ it states "conda: Command not found.“
Do you have suggestions on how to proceed or shall I wait until tomorrow morning for the installation help session?"*

**Comment by jhunkeler** [comment]
- Delete `/Applications/anaconda` (or `/Applications/anaconda3` in the case of Python 3)
- Use the `.sh` installer instead of the `.pkg` variant

If they can no longer edit their .bashrc: `sudo chmod 644 ~/.bashrc`
If they no longer own .bashrc: `sudo chown username: ~/.bashrc` (yes the ':' suffix is required so the group is reset as well)

If the installer doesn't do this for them, they need to add the following to the end of their .bashrc, then open a new terminal:

```
# example path... use a valid path here
export PATH=$HOME/path/to/anaconda/bin:$PATH
```

**Comment by dnhyde** [comment]
Hi instead of reinstalling everything I added a symlink to conda (assuming everything is fine in .profile or .bash_profile or .bashrc).
I did the following and it worked for me:
`ln -s "Applications/anaconda/bin/conda" /usr/local/bin/conda `

Hope this helps

**Comment by freemansion** [comment]
thanks @dnhyde. I had another issue with conda and your solution solved it!
