### ISSUE TITLE
Move table grouping into advanced tables?

### ISSUE THREAD

**Issue by taldcroft** [spacetelescope/JWSTUserTraining2016#4]
@tepickering - the last exercise in Tables_Pandas.ipynb is likely to be fairly challenging without any previous explanation.  I think this is good as an advanced table topic and I would like to cover grouping in some detail in my talk.  Could you take this exercise out?

**Comment by tepickering** [comment]
sure, no problem.  the current version was just lifted directly from what i did at the AAS in january.  i went a little deeper since it was the only Tables tutorial given there.  since we have more time for this workshop, it makes a lot more sense to keep the Day 0 stuff intro/high-level and leave the more advanced stuff for your tutorial.

**Comment by taldcroft** [comment]
@tepickering - BTW, do you have plans for additional topics or material in your day-0 session or does this current notebook mostly cover it?

**Comment by tepickering** [comment]
i'm in the process of collecting some more stuff to add to it or use in lieu of, e.g. some Gaia-related examples and fleshing out more on pandas.  wasn't planning on going into more `astropy.table` detail, though.
